In [2]:
import pandas as pd
import sqlite3

# Load CSV
df = pd.read_csv("../data/synthetic/orders_data.csv")

# Create SQLite database
conn = sqlite3.connect("../data/processed/zepto.db")

# Store table
df.to_sql(
    "orders",
    conn,
    if_exists="replace",
    index=False
)

print("Database created successfully 😤")

Database created successfully 😤

In [3]:
query = """

SELECT
    city,
    ROUND(AVG(contribution_margin),2) AS avg_margin,
    ROUND(AVG(order_value),2) AS avg_order_value,
    COUNT(*) AS total_orders

FROM orders

GROUP BY city

ORDER BY avg_margin DESC

"""

city_analysis = pd.read_sql_query(query, conn)

city_analysis

        city  avg_margin  avg_order_value  total_orders
0     Mumbai      -10.97           449.77          3408
1  Hyderabad      -11.73           451.33          3294
2       Pune      -12.13           450.98          3346
3      Delhi      -12.15           447.61          3376
4    Chennai      -12.44           450.15          3247
5  Bangalore      -12.58           448.89          3329

In [4]:
import plotly.express as px

fig = px.bar(
    city_analysis,
    x="city",
    y="avg_margin",
    color="avg_margin",
    title="Average Contribution Margin by City"
)

fig.show()

In [5]:
query = """

SELECT
    customer_type,
    ROUND(AVG(contribution_margin),2) AS avg_profit,
    ROUND(AVG(order_value),2) AS avg_aov,
    COUNT(*) AS total_orders

FROM orders

GROUP BY customer_type

ORDER BY avg_profit DESC

"""

customer_analysis = pd.read_sql_query(query, conn)

customer_analysis

     customer_type  avg_profit  avg_aov  total_orders
0          Regular      -11.58   452.41          9981
1  Discount-Seeker      -12.05   449.08          4964
2          Premium      -12.76   445.27          5055

In [6]:
fig = px.scatter(
    customer_analysis,
    x="avg_aov",
    y="avg_profit",
    size="total_orders",
    color="customer_type",
    title="Customer Segment Profitability"
)

fig.show()